---
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

name: Dependabot auto-merge
on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge on the PR
        uses: devon-mar/auto-merge-action@master
        with:
          app_id: ${{ secrets.AUTO_MERGE_APP_ID }}
          app_private_key: ${{ secrets.AUTO_MERGE_APP_PRIVATE_KEY }}
