---
name: test

"on":
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone netbox-docker
        uses: actions/checkout@v4
        with:
          repository: netbox-community/netbox-docker
          path: netbox-docker

      - name: Checkout the latest netbox-docker tag
        working-directory: ${{ github.workspace }}/netbox-docker
        run: |
          git checkout $(git describe --tags `git rev-list --tags --max-count=1`)

      - run: |
          ./test/test.sh

      - name: Show Docker logs
        if: ${{ always() }}
        run: docker-compose logs
        working-directory: ./netbox-docker/
